spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imweb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: validate
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.type: trace